version: "3.8"
services:
  app:
    container_name: restaurant_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_FLAGS=--legacy-peer-deps
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - DATABASE_URL=mysql://restaurant_user:restaurant_password@mysql:3306/restaurant_db
      - NEXTAUTH_SECRET=your-deployment-secret-key-change-me
      - NEXTAUTH_URL=http://localhost
      - NODE_ENV=production
      - NEXT_PUBLIC_SKIP_ESLINT_CHECK=true
      - DEBUG=1
    depends_on:
      - mysql
    networks:
      - restaurant_network

  mysql:
    image: mysql:8.0
    container_name: restaurant_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - restaurant_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  restaurant_network:
    driver: bridge

volumes:
  mysql_data:
